BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'

    Label:
        id: result_label
        color: (1, 1, 0, 1)
